# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/alos',
                'doc_host': 'https://a-diamant.github.io',
                'git_url': 'https://github.com/a-diamant/alos',
                'lib_path': 'alos'},
  'syms': {'alos.core': {'alos.core.foo': ('core.html#foo', 'alos/core.py')}}}
